const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, '..', 'data', 'questions', 'team.json');
const existing = JSON.parse(fs.readFileSync(FILE, 'utf8'));
console.log('Existing:', existing.length);

const newQ = [
  // ── MC: Soomaaliya ──
  {"question":"Luuqadda Soomaaliga si rasmi ah loo qoray sanadkii?","options":["1960","1969","1972","1979"],"correct":"1972"},
  {"question":"Caasimadda gobolka Galmudug waa?","options":["Gaalkacyo","Dhuusamarreeb","Hobyo","Cadaado"],"correct":"Dhuusamarreeb"},
  {"question":"Caasimadda gobolka Bay waa?","options":["Baraawe","Afgooye","Jawhar","Baidoa"],"correct":"Baidoa"},
  {"question":"Gobolka Shabeellaha Dhexe caasimaddiisu waa?","options":["Marka","Afgooye","Jawhar","Balcad"],"correct":"Jawhar"},
  {"question":"Caasimadda gobolka Jubbada Sare waa?","options":["Kismaayo","Luuq","Bu'aale","Baraawe"],"correct":"Bu'aale"},
  {"question":"Caasimadda gobolka Galgaduud waa?","options":["Gaalkacyo","Dhuusamarreeb","Ceel Buur","Baardheere"],"correct":"Dhuusamarreeb"},
  {"question":"Caasimadda gobolka Mudug waa?","options":["Dhuusamarreeb","Hobyo","Gaalkacyo","Ceel Buur"],"correct":"Gaalkacyo"},
  {"question":"Caasimadda gobolka Nugaal waa?","options":["Boosaaso","Eyl","Qardho","Garoowe"],"correct":"Garoowe"},
  {"question":"Caasimadda gobolka Bari waa?","options":["Garoowe","Eyl","Qardho","Boosaaso"],"correct":"Boosaaso"},
  {"question":"Caasimadda gobolka Shabeellaha Hoose waa?","options":["Afgooye","Jawhar","Marka","Baraawe"],"correct":"Marka"},
  // ── MC: Islaamka ──
  {"question":"Tirada juz'yada Qur'aanka waa?","options":["25","28","30","32"],"correct":"30"},
  {"question":"Bisha Ramadaan waa bisha?","options":["7aad","8aad","9aad","10aad"],"correct":"9aad"},
  {"question":"Nabi Ibraahim (AS) wuxuu dhisay?","options":["Masjidka Aqsaa","Kacbada","Masjidka Nabiga","Masjidka Qubaa"],"correct":"Kacbada"},
  {"question":"Suuradda 36 ee Qur'aanka magaceedu waa?","options":["Al-Kahf","Maryam","Luqmaan","Yaasiin"],"correct":"Yaasiin"},
  {"question":"Nabi Yuusuf (AS) wuxuu ku noolaa?","options":["Shaam","Ciraaq","Masar","Xijaasku"],"correct":"Masar"},
  {"question":"Tirada sujuudda saladadda Fajriga waa?","options":["2","3","4","6"],"correct":"4"},
  {"question":"Kitaabka Zabuura waxaa lagu soo dejiyay?","options":["Nabi Muuse","Nabi Ciise","Nabi Ibraahim","Nabi Daawuud"],"correct":"Nabi Daawuud"},
  {"question":"Tirada Nebiyada Ulul-Cazm waa?","options":["4","5","6","7"],"correct":"5"},
  {"question":"Ciida Xajka waxay ku beegan tahay bisha?","options":["Ramadaan","Shawwaal","Dhul-Qacda","Dhul-Xijjah"],"correct":"Dhul-Xijjah"},
  {"question":"Nabi Muuse (AS) meesha uu ka yimid waa?","options":["Shaam","Ciraaq","Masar","Xijaasku"],"correct":"Masar"},
  // ── MC: Xisaabta ──
  {"question":"Waa maxay √225?","options":["13","14","15","16"],"correct":"15"},
  {"question":"Waa maxay 9²?","options":["72","81","91","99"],"correct":"81"},
  {"question":"Waa maxay 2¹⁰?","options":["512","1024","2048","4096"],"correct":"1024"},
  {"question":"Waa maxay 15% of 200?","options":["25","30","35","40"],"correct":"30"},
  {"question":"Waa maxay 17 × 17?","options":["279","289","299","309"],"correct":"289"},
  {"question":"Waa maxay 4!?","options":["12","16","20","24"],"correct":"24"},
  {"question":"Waa maxay 0.5 × 0.5?","options":["0.1","0.25","0.5","1"],"correct":"0.25"},
  {"question":"Tirada xagasha hexagon (shax) waa?","options":["5","6","7","8"],"correct":"6"},
  {"question":"Waa maxay 50% of 300?","options":["100","125","150","175"],"correct":"150"},
  {"question":"Waa maxay √49?","options":["5","6","7","8"],"correct":"7"},
  // ── MC: Sayniska ──
  {"question":"Meeraha ugu dhow qorraxda waa?","options":["Venus","Earth","Mars","Mercury"],"correct":"Mercury"},
  {"question":"Tirada meeraha nidaamka qorraxeed waa?","options":["7","8","9","10"],"correct":"8"},
  {"question":"Xayawaanka ugu dheer adduunka waa?","options":["Giraffe","Elephant","Camel","Ostrich"],"correct":"Giraffe"},
  {"question":"Xayawaanka ugu weyn adduunka waa?","options":["Elephant","Whale Shark","Blue Whale","Sperm Whale"],"correct":"Blue Whale"},
  {"question":"Tirada chromosomes bini'aadamka waa?","options":["23","44","46","48"],"correct":"46"},
  {"question":"Oksijiinta lambarka atoomiga waa?","options":["6","7","8","9"],"correct":"8"},
  {"question":"Dheriska iftiinka (km/s) waa?","options":["100,000","200,000","300,000","400,000"],"correct":"300,000"},
  {"question":"Xubinta jirka ugu weyn waa?","options":["Beerka","Maskaxda","Maqaarka","Wadnaha"],"correct":"Maqaarka"},
  {"question":"Meeraha ugu weyn nidaamka qorraxeed waa?","options":["Saturn","Neptune","Uranus","Jupiter"],"correct":"Jupiter"},
  {"question":"Meeraha ugu fog qorraxda waa?","options":["Uranus","Saturn","Jupiter","Neptune"],"correct":"Neptune"},
  // ── MC: Juqraafiyada ──
  {"question":"Caasimadda Australia waa?","options":["Sydney","Melbourne","Brisbane","Canberra"],"correct":"Canberra"},
  {"question":"Caasimadda Brazil waa?","options":["Rio de Janeiro","São Paulo","Salvador","Brasília"],"correct":"Brasília"},
  {"question":"Caasimadda Argentina waa?","options":["Córdoba","Rosario","Mendoza","Buenos Aires"],"correct":"Buenos Aires"},
  {"question":"Caasimadda Mexico waa?","options":["Guadalajara","Monterrey","Puebla","Mexico City"],"correct":"Mexico City"},
  {"question":"Webiga ugu dhaadheer Yurub waa?","options":["Rhine","Danube","Thames","Volga"],"correct":"Volga"},
  {"question":"Buurta ugu sarreysa Aafrika waa?","options":["Mt. Kenya","Atlas","Rwenzori","Kilimanjaro"],"correct":"Kilimanjaro"},
  {"question":"Dalka ugu yar adduunka waa?","options":["Monaco","San Marino","Liechtenstein","Vatican City"],"correct":"Vatican City"},
  {"question":"Caasimadda Pakistan waa?","options":["Karachi","Lahore","Quetta","Islamabad"],"correct":"Islamabad"},
  {"question":"Caasimadda Japan waa?","options":["Osaka","Kyoto","Nagoya","Tokyo"],"correct":"Tokyo"},
  {"question":"Caasimadda South Korea waa?","options":["Busan","Incheon","Daegu","Seoul"],"correct":"Seoul"},
  {"question":"Caasimadda Indonesia waa?","options":["Surabaya","Bandung","Medan","Jakarta"],"correct":"Jakarta"},
  {"question":"Caasimadda Nigeria waa?","options":["Lagos","Kano","Ibadan","Abuja"],"correct":"Abuja"},
  {"question":"Caasimadda Morocco waa?","options":["Casablanca","Fes","Marrakech","Rabat"],"correct":"Rabat"},
  {"question":"Caasimadda Algeria waa?","options":["Oran","Constantine","Annaba","Algiers"],"correct":"Algiers"},
  {"question":"Caasimadda Sweden waa?","options":["Gothenburg","Malmö","Uppsala","Stockholm"],"correct":"Stockholm"},
  {"question":"Caasimadda Norway waa?","options":["Bergen","Trondheim","Stavanger","Oslo"],"correct":"Oslo"},
  {"question":"Caasimadda Poland waa?","options":["Kraków","Łódź","Wrocław","Warsaw"],"correct":"Warsaw"},
  {"question":"Caasimadda Ukraine waa?","options":["Kharkiv","Odessa","Lviv","Kyiv"],"correct":"Kyiv"},
  {"question":"Caasimadda Iran waa?","options":["Mashhad","Isfahan","Shiraz","Tehran"],"correct":"Tehran"},
  {"question":"Caasimadda Libya waa?","options":["Benghazi","Misrata","Tobruk","Tripoli"],"correct":"Tripoli"},
  // ── MC: Teknoolajiyada ──
  {"question":"RAM waxay u dhigan tahay?","options":["Read Access Memory","Remote Access Memory","Regular Access Memory","Random Access Memory"],"correct":"Random Access Memory"},
  {"question":"HTML waxay u dhigan tahay?","options":["HyperText Media Language","HyperText Markup Language","HighText Markup Language","HyperTool Markup Language"],"correct":"HyperText Markup Language"},
  {"question":"Python waxaa sameeyay?","options":["Dennis Ritchie","James Gosling","Linus Torvalds","Guido van Rossum"],"correct":"Guido van Rossum"},
  {"question":"Facebook waxaa la aasaasay sanadkii?","options":["2002","2003","2004","2005"],"correct":"2004"},
  {"question":"iPhone-ka ugu horreeyay waxaa la soo saaray sanadkii?","options":["2005","2006","2007","2008"],"correct":"2007"},
  {"question":"Linux kernel waxaa sameeyay?","options":["Bill Gates","Dennis Ritchie","Steve Jobs","Linus Torvalds"],"correct":"Linus Torvalds"},
  {"question":"URL waxay u dhigan tahay?","options":["Uniform Resource Locator","Universal Resource Link","Unique Reference Locator","Unified Resource Language"],"correct":"Uniform Resource Locator"},
  {"question":"OS-ka Apple iPhoneyaasha waa?","options":["Android","Windows","HarmonyOS","iOS"],"correct":"iOS"},
  {"question":"Google waxaa la aasaasay sanadkii?","options":["1996","1997","1998","1999"],"correct":"1998"},
  {"question":"USB waxay u dhigan tahay?","options":["Universal System Bus","Universal Serial Bus","Unified Serial Bus","Unique Serial Bus"],"correct":"Universal Serial Bus"},
  // ── MC: Luuqadda Ingiriisiga ──
  {"question":"What is the past tense of 'write'?","options":["writed","written","wroted","wrote"],"correct":"wrote"},
  {"question":"What is the plural of 'tooth'?","options":["tooths","toothes","teeths","teeth"],"correct":"teeth"},
  {"question":"What is the plural of 'foot'?","options":["foots","footes","feets","feet"],"correct":"feet"},
  {"question":"What does 'rapid' mean?","options":["Slow","Careful","Heavy","Fast"],"correct":"Fast"},
  {"question":"What is the past tense of 'fly'?","options":["flied","flyed","flown","flew"],"correct":"flew"},
  {"question":"What is the past tense of 'run'?","options":["runned","raned","ranned","ran"],"correct":"ran"},
  {"question":"What is the past tense of 'swim'?","options":["swimmed","swammed","swum","swam"],"correct":"swam"},
  {"question":"What is the opposite of 'arrive'?","options":["Come","Go","Stay","Depart"],"correct":"Depart"},
  {"question":"What does 'enormous' mean?","options":["Tiny","Ordinary","Dangerous","Very large"],"correct":"Very large"},
  {"question":"What is the plural of 'man'?","options":["mans","manes","manses","men"],"correct":"men"},
  // ── MC: Taariikhda ──
  {"question":"Dagaalkii Labaad ee Adduunka wuxuu billaaday sanadkii?","options":["1937","1938","1939","1940"],"correct":"1939"},
  {"question":"WWII wuxuu dhammaaday sanadkii?","options":["1943","1944","1945","1946"],"correct":"1945"},
  {"question":"Neil Armstrong dayaxa ku dhuftay sanadkii?","options":["1967","1968","1969","1970"],"correct":"1969"},
  {"question":"Suez Canal waxaa la furay sanadkii?","options":["1859","1869","1879","1889"],"correct":"1869"},
  {"question":"WWI wuxuu billaaday sanadkii?","options":["1912","1913","1914","1915"],"correct":"1914"},
  {"question":"Madaxweynihii ugu horreeyay USA waa?","options":["Thomas Jefferson","John Adams","Benjamin Franklin","George Washington"],"correct":"George Washington"},
  {"question":"Nelson Mandela madaxweyne noqday sanadkii?","options":["1990","1992","1994","1996"],"correct":"1994"},
  {"question":"Titanic gashay biyaha sanadkii?","options":["1910","1911","1912","1913"],"correct":"1912"},
  {"question":"Columbus gaadhay Ameerika sanadkii?","options":["1488","1490","1492","1494"],"correct":"1492"},
  {"question":"WWI wuxuu dhammaaday sanadkii?","options":["1916","1917","1918","1919"],"correct":"1918"},

  // ════════════════════════════════════════════
  // ── BEEN (False T/F) ──
  // ════════════════════════════════════════════
  {"question":"Caasimadda Australia waa Sydney.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Brazil waa Rio de Janeiro.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Argentina waa Córdoba.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Mexico waa Guadalajara.","options":["Run","Been"],"correct":"Been"},
  {"question":"Webiga ugu dhaadheer Yurub waa Danube.","options":["Run","Been"],"correct":"Been"},
  {"question":"Meeraha ugu dhow qorraxda waa Venus.","options":["Run","Been"],"correct":"Been"},
  {"question":"Meeraha ugu weyn qorraxeed waa Saturn.","options":["Run","Been"],"correct":"Been"},
  {"question":"Meeraha ugu fog qorraxda waa Uranus.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada chromosomes bini'aadamka waa 44.","options":["Run","Been"],"correct":"Been"},
  {"question":"Xubinta jirka ugu weyn waa Beerka.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Pakistan waa Karachi.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Japan waa Osaka.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda South Korea waa Busan.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Indonesia waa Surabaya.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Nigeria waa Lagos.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Morocco waa Casablanca.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Algeria waa Oran.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Libya waa Benghazi.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Sweden waa Gothenburg.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Norway waa Bergen.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Poland waa Kraków.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Ukraine waa Kharkiv.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Iran waa Mashhad.","options":["Run","Been"],"correct":"Been"},
  {"question":"9² = 72.","options":["Run","Been"],"correct":"Been"},
  {"question":"2¹⁰ = 512.","options":["Run","Been"],"correct":"Been"},
  {"question":"√225 = 14.","options":["Run","Been"],"correct":"Been"},
  {"question":"4! = 16.","options":["Run","Been"],"correct":"Been"},
  {"question":"0.5 × 0.5 = 1.","options":["Run","Been"],"correct":"Been"},
  {"question":"50% of 300 waa 125.","options":["Run","Been"],"correct":"Been"},
  {"question":"√49 = 6.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada xagasha hexagon waa 7.","options":["Run","Been"],"correct":"Been"},
  {"question":"17 × 17 = 279.","options":["Run","Been"],"correct":"Been"},
  {"question":"15% of 200 waa 25.","options":["Run","Been"],"correct":"Been"},
  {"question":"WWII wuxuu billaaday 1940.","options":["Run","Been"],"correct":"Been"},
  {"question":"WWII wuxuu dhammaaday 1946.","options":["Run","Been"],"correct":"Been"},
  {"question":"Neil Armstrong dayaxa ku dhuftay 1971.","options":["Run","Been"],"correct":"Been"},
  {"question":"WWI wuxuu billaaday 1916.","options":["Run","Been"],"correct":"Been"},
  {"question":"WWI wuxuu dhammaaday 1920.","options":["Run","Been"],"correct":"Been"},
  {"question":"Madaxweynihii ugu horreeyay USA waa Thomas Jefferson.","options":["Run","Been"],"correct":"Been"},
  {"question":"Nelson Mandela madaxweyne noqday 1990.","options":["Run","Been"],"correct":"Been"},
  {"question":"Titanic gashay biyaha 1915.","options":["Run","Been"],"correct":"Been"},
  {"question":"Columbus gaadhay Ameerika 1502.","options":["Run","Been"],"correct":"Been"},
  {"question":"Facebook waxaa la aasaasay 2006.","options":["Run","Been"],"correct":"Been"},
  {"question":"iPhone-ka ugu horreeyay waxaa la soo saaray 2008.","options":["Run","Been"],"correct":"Been"},
  {"question":"HTML waxay u dhigan tahay HyperText Media Language.","options":["Run","Been"],"correct":"Been"},
  {"question":"Python waxaa sameeyay Dennis Ritchie.","options":["Run","Been"],"correct":"Been"},
  {"question":"Linux waxaa sameeyay Bill Gates.","options":["Run","Been"],"correct":"Been"},
  {"question":"Google waxaa la aasaasay 2001.","options":["Run","Been"],"correct":"Been"},
  {"question":"USB waxay u dhigan tahay Universal System Bus.","options":["Run","Been"],"correct":"Been"},
  {"question":"RAM waxay u dhigan tahay Read Access Memory.","options":["Run","Been"],"correct":"Been"},
  {"question":"URL waxay u dhigan tahay Universal Resource Link.","options":["Run","Been"],"correct":"Been"},
  {"question":"OS-ka Apple waa Android.","options":["Run","Been"],"correct":"Been"},
  {"question":"Plural of 'tooth' waa 'tooths'.","options":["Run","Been"],"correct":"Been"},
  {"question":"Plural of 'foot' waa 'foots'.","options":["Run","Been"],"correct":"Been"},
  {"question":"Past tense of 'fly' waa 'flied'.","options":["Run","Been"],"correct":"Been"},
  {"question":"Past tense of 'run' waa 'runned'.","options":["Run","Been"],"correct":"Been"},
  {"question":"Past tense of 'swim' waa 'swimmed'.","options":["Run","Been"],"correct":"Been"},
  {"question":"Past tense of 'write' waa 'written'.","options":["Run","Been"],"correct":"Been"},
  {"question":"Plural of 'man' waa 'mans'.","options":["Run","Been"],"correct":"Been"},
  {"question":"'Rapid' macnaheedu waa 'Slow'.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada juz'yada Qur'aanka waa 28.","options":["Run","Been"],"correct":"Been"},
  {"question":"Ramadaan waa bisha 8-aad ee Islaamka.","options":["Run","Been"],"correct":"Been"},
  {"question":"Nabi Ibraahim wuxuu dhisay Masjidka Aqsaa.","options":["Run","Been"],"correct":"Been"},
  {"question":"Suuradda 36 waa Maryam.","options":["Run","Been"],"correct":"Been"},
  {"question":"Nabi Yuusuf (AS) wuxuu ku noolaa Shaam.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada Nebiyada Ulul-Cazm waa 6.","options":["Run","Been"],"correct":"Been"},
  {"question":"Kitaabka Zabuura waxaa lagu soo dejiyay Nabi Ciise.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada sujuudda Fajriga waa 2.","options":["Run","Been"],"correct":"Been"},
  {"question":"Ciida Xajka waxay ku beegan tahay bisha Ramadaan.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda gobolka Galmudug waa Gaalkacyo.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda gobolka Bay waa Afgooye.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda gobolka Galgaduud waa Gaalkacyo.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda gobolka Mudug waa Dhuusamarreeb.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda gobolka Nugaal waa Qardho.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda gobolka Bari waa Eyl.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda gobolka Shabeellaha Hoose waa Afgooye.","options":["Run","Been"],"correct":"Been"},
  {"question":"Luuqadda Soomaaliga si rasmi ah loo qoray 1980.","options":["Run","Been"],"correct":"Been"},
  {"question":"Gobolka ugu weyn Soomaaliya dhulkiisa waa Gedo.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda gobolka Jubbada Sare waa Kismaayo.","options":["Run","Been"],"correct":"Been"},
  {"question":"Meeraha ugu dhow qorraxda waa Earth.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada lafahaa jirka bini'aadamka waa 200.","options":["Run","Been"],"correct":"Been"},
  {"question":"Oksijiinta lambarka atoomiga waa 10.","options":["Run","Been"],"correct":"Been"},
  {"question":"Xayawaanka ugu dheer adduunka waa Elephant.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada meeraha nidaamka qorraxeed waa 9.","options":["Run","Been"],"correct":"Been"},
  {"question":"Dheriska iftiinka waa 200,000 km/s.","options":["Run","Been"],"correct":"Been"},
  {"question":"Xayawaanka ugu weyn adduunka waa Whale Shark.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada caleemaha bandhiga waa 115.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda gobolka Shabeellaha Dhexe waa Marka.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda gobolka Hiiraan waa Bulo Burde.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada sanadaha qarni waa 50.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada bilaha sanadka waa 10.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada saacadaha maalinta waa 20.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada maalinta toddobaadka waa 6.","options":["Run","Been"],"correct":"Been"},
  {"question":"π ilaa labo meelood waa 3.16.","options":["Run","Been"],"correct":"Been"},
  {"question":"Buurta ugu sarreysa Aafrika waa Mt. Kenya.","options":["Run","Been"],"correct":"Been"},
  {"question":"Dalka ugu yar adduunka waa Monaco.","options":["Run","Been"],"correct":"Been"},
  {"question":"Webiga ugu dhaadheer adduunka waa Congo.","options":["Run","Been"],"correct":"Been"},
  {"question":"Badda ugu weyn adduunka waa Atlantik.","options":["Run","Been"],"correct":"Been"},
  {"question":"Buurta ugu sarreysa adduunka waa K2.","options":["Run","Been"],"correct":"Been"},
  {"question":"Dalkii ugu horreeyay ee gaadhay dayaxa waa Ruushka.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda dalka Sacuudiga waa Jidda.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda dalka Imaaraatka waa Dubai.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda dalka Qadar waa Riyadh.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda dalka Hindiya waa Mumbai.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda dalka Shiinaha waa Shanghai.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda dalka Ruushka waa St. Petersburg.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda dalka Kanada waa Toronto.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda dalka Turkiga waa Istanbul.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda dalka Faransiiska waa Lyon.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda dalka Jarmalka waa Munich.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda dalka Ingiriiska waa Manchester.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda dalka Itoobiya waa Dire Dawa.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda dalka Kenya waa Mombasa.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda dalka Masar waa Alexandria.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada Suurtada Qur'aanka waa 110.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada halqabihii Raashidiin waa 3.","options":["Run","Been"],"correct":"Been"},
  {"question":"Halqabihii Islaamkii ugu horreeyay waa Cumar.","options":["Run","Been"],"correct":"Been"},
  {"question":"Sannadkii Hijriga bilaabatay waa 615 M.","options":["Run","Been"],"correct":"Been"},
  {"question":"Kitaabka Tawraadda waxaa lagu soo dejiyay Nabi Ciise.","options":["Run","Been"],"correct":"Been"},
  {"question":"Nabi Muxamed (CSW) wuxuu ku dhashay Madiina.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada fariidhyada Islaamka waa 4.","options":["Run","Been"],"correct":"Been"},
  {"question":"15 × 15 = 215.","options":["Run","Been"],"correct":"Been"},
  {"question":"√144 = 13.","options":["Run","Been"],"correct":"Been"},
  {"question":"8 × 9 = 63.","options":["Run","Been"],"correct":"Been"},
  {"question":"20% of 500 waa 75.","options":["Run","Been"],"correct":"Been"},
  {"question":"5! = 60.","options":["Run","Been"],"correct":"Been"},
  {"question":"3³ = 36.","options":["Run","Been"],"correct":"Been"},
  {"question":"12² = 156.","options":["Run","Been"],"correct":"Been"},
  {"question":"25 × 4 = 90.","options":["Run","Been"],"correct":"Been"},
  {"question":"1000 ÷ 25 = 30.","options":["Run","Been"],"correct":"Been"},
  {"question":"2⁸ = 128.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada xagasha saddex-xagalka waa 270°.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada xagasha afar-xagalka waa 270°.","options":["Run","Been"],"correct":"Been"},
  {"question":"Nooca dhiigga ugu guud adduunka waa A+.","options":["Run","Been"],"correct":"Been"},
  {"question":"Heerkulka jirka bini'aadamka waa 39°C.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada garaaca wadnaha caadiga waa 110-130.","options":["Run","Been"],"correct":"Been"},
  {"question":"Dhibcaha biyuhu karkaraan waa 90°C.","options":["Run","Been"],"correct":"Been"},
  {"question":"Cunto cagaaran waxay samaysan tahay mitokondria.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada carboonka jadwalka waa 8.","options":["Run","Been"],"correct":"Been"},
  {"question":"Xubinta jirka nuujinta dhiigga waa Sambabbada.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada cabirada bini'aadamka waa 3.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada sambabbada bini'aadamka waa 3.","options":["Run","Been"],"correct":"Been"},
  {"question":"Hantida ugu qaali badan adduunka waa Dahabka.","options":["Run","Been"],"correct":"Been"},
  {"question":"Xiddigta ugu dhowaanta qorraxda waa Sirius.","options":["Run","Been"],"correct":"Been"},
  {"question":"Madaxweynihii ugu horreeyay Soomaaliya waa Maxamed Siyaad Barre.","options":["Run","Been"],"correct":"Been"},
  {"question":"Kismaayo waxay ku taal gobolka Jubbada Sare.","options":["Run","Been"],"correct":"Been"},
  {"question":"Webiga Shabelle waa kan ugu dhaadheer Soomaaliya.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda gobolka Woqooyi Bari (Puntland) waa Qardho.","options":["Run","Been"],"correct":"Been"},
  {"question":"Brazil wuxuu FIFA World Cup 6 jeer ku guulaystay.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada ciyaaryahanada volleyball koox waa 7.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada innings baseball waa 12.","options":["Run","Been"],"correct":"Been"},
  {"question":"Olympics-ka sanadkii laba jeer ayuu dhacaa.","options":["Run","Been"],"correct":"Been"},
  {"question":"World Cup 2022 ku guulaystay kooxda Faransiiska.","options":["Run","Been"],"correct":"Been"},
  {"question":"World Cup 2018 ku guulaystay kooxda Germany.","options":["Run","Been"],"correct":"Been"},
  {"question":"World Cup ugu horreeyay waxay dhacday 1934.","options":["Run","Been"],"correct":"Been"},
  {"question":"Kooxda kubadda cagta FIFA WC ugu badan guulaystay waa Germany.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Iran waa Isfahan.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Morocco waa Fes.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Nigeria waa Kano.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Indonesia waa Bandung.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Pakistan waa Lahore.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Japan waa Kyoto.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda South Korea waa Incheon.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Ukraine waa Odessa.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Poland waa Łódź.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Sweden waa Malmö.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Norway waa Trondheim.","options":["Run","Been"],"correct":"Been"},
  {"question":"9 × 8 = 63.","options":["Run","Been"],"correct":"Been"},
  {"question":"7 × 9 = 56.","options":["Run","Been"],"correct":"Been"},
  {"question":"6 × 8 = 42.","options":["Run","Been"],"correct":"Been"},
  {"question":"9 × 9 = 80.","options":["Run","Been"],"correct":"Been"},
  {"question":"6 × 7 = 48.","options":["Run","Been"],"correct":"Been"},
  {"question":"8 × 8 = 72.","options":["Run","Been"],"correct":"Been"},
  {"question":"5 × 6 = 35.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Libya waa Benghazi.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Algeria waa Constantine.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Brazil waa São Paulo.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Australia waa Melbourne.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Argentina waa Rosario.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Mexico waa Monterrey.","options":["Run","Been"],"correct":"Been"},
  {"question":"Webiga ugu dhaadheer Yurub waa Rhine.","options":["Run","Been"],"correct":"Been"},
  {"question":"Dalka ugu yar adduunka waa San Marino.","options":["Run","Been"],"correct":"Been"},
  {"question":"Buurta ugu sarreysa Aafrika waa Atlas.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada bilaha Febraayo ee sanadka caadiga ah waa 30.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada daqiiqadaha saacadda waa 100.","options":["Run","Been"],"correct":"Been"},
  {"question":"Oksijiinta lambarka atoomiga waa 6.","options":["Run","Been"],"correct":"Been"},
  {"question":"Carboonka lambarka atoomiga waa 8.","options":["Run","Been"],"correct":"Been"},
  {"question":"Nooca dhiigga ugu guud adduunka waa B+.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada lafahaa jirka bini'aadamka waa 216.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada lafahaa jirka bini'aadamka waa 196.","options":["Run","Been"],"correct":"Been"},
  {"question":"Xubinta jirka nuujinta oksijiinta waa Wadnaha.","options":["Run","Been"],"correct":"Been"},
  {"question":"Cunto kasta oo cagaaran waxay samaysan tahay nukliyaas.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada garaaca wadnaha daqiiqadda waa 40-50.","options":["Run","Been"],"correct":"Been"},
  {"question":"Heerkulka jirka bini'aadamka waa 35°C.","options":["Run","Been"],"correct":"Been"},
  {"question":"Heerkulka jirka bini'aadamka waa 41°C.","options":["Run","Been"],"correct":"Been"},
  {"question":"Dhibcaha biyuhu karkaraan waa 80°C.","options":["Run","Been"],"correct":"Been"},
  {"question":"Suez Canal waxaa la furay 1880.","options":["Run","Been"],"correct":"Been"},
  {"question":"WWI wuxuu billaaday 1912.","options":["Run","Been"],"correct":"Been"},
  {"question":"Titanic gashay biyaha 1910.","options":["Run","Been"],"correct":"Been"},
  {"question":"Columbus gaadhay Ameerika 1488.","options":["Run","Been"],"correct":"Been"},
  {"question":"Nelson Mandela madaxweyne noqday 1992.","options":["Run","Been"],"correct":"Been"},
  {"question":"WWII wuxuu billaaday 1938.","options":["Run","Been"],"correct":"Been"},
  {"question":"Neil Armstrong dayaxa ku dhuftay 1967.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda gobolka Woqooyi Bari (Puntland) waa Garoowe.","options":["Run","Been"],"correct":"Been"},
  {"question":"Facebook waxaa la aasaasay 2010.","options":["Run","Been"],"correct":"Been"},
  {"question":"iPhone-ka ugu horreeyay waxaa la soo saaray 2010.","options":["Run","Been"],"correct":"Been"},
  {"question":"Python waxaa sameeyay James Gosling.","options":["Run","Been"],"correct":"Been"},
  {"question":"Linux waxaa sameeyay Dennis Ritchie.","options":["Run","Been"],"correct":"Been"},
  {"question":"Google waxaa la aasaasay 2005.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Soomaaliya waa Hargeysa.","options":["Run","Been"],"correct":"Been"},
  {"question":"Maalin Xorriyadda Koonfurta Soomaaliya waa 26 Juun.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Puntland waa Boosaaso.","options":["Run","Been"],"correct":"Been"},
  {"question":"Gobolka ugu weyn dhulkiisa Soomaaliya waa Hiiraan.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada gobollada Soomaaliya waa 21.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada gobollada Soomaaliya waa 24.","options":["Run","Been"],"correct":"Been"},

  // ── RUN (True T/F) ──
  {"question":"Caasimadda Australia waa Canberra.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Brazil waa Brasília.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Argentina waa Buenos Aires.","options":["Run","Been"],"correct":"Run"},
  {"question":"Meeraha ugu dhow qorraxda waa Mercury.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada meeraha nidaamka qorraxeed waa 8.","options":["Run","Been"],"correct":"Run"},
  {"question":"Xayawaanka ugu dheer adduunka waa Giraffe.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada chromosomes bini'aadamka waa 46.","options":["Run","Been"],"correct":"Run"},
  {"question":"Oksijiinta lambarka atoomiga waa 8.","options":["Run","Been"],"correct":"Run"},
  {"question":"Meeraha ugu weyn nidaamka qorraxeed waa Jupiter.","options":["Run","Been"],"correct":"Run"},
  {"question":"Meeraha ugu fog qorraxda waa Neptune.","options":["Run","Been"],"correct":"Run"},
  {"question":"9² = 81.","options":["Run","Been"],"correct":"Run"},
  {"question":"2¹⁰ = 1024.","options":["Run","Been"],"correct":"Run"},
  {"question":"√225 = 15.","options":["Run","Been"],"correct":"Run"},
  {"question":"4! = 24.","options":["Run","Been"],"correct":"Run"},
  {"question":"50% of 300 waa 150.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada xagasha hexagon waa 6.","options":["Run","Been"],"correct":"Run"},
  {"question":"WWII wuxuu billaaday 1939.","options":["Run","Been"],"correct":"Run"},
  {"question":"WWII wuxuu dhammaaday 1945.","options":["Run","Been"],"correct":"Run"},
  {"question":"Neil Armstrong dayaxa ku dhuftay 1969.","options":["Run","Been"],"correct":"Run"},
  {"question":"WWI wuxuu billaaday 1914.","options":["Run","Been"],"correct":"Run"},
  {"question":"WWI wuxuu dhammaaday 1918.","options":["Run","Been"],"correct":"Run"},
  {"question":"Titanic gashay biyaha 1912.","options":["Run","Been"],"correct":"Run"},
  {"question":"Columbus gaadhay Ameerika 1492.","options":["Run","Been"],"correct":"Run"},
  {"question":"Madaxweynihii ugu horreeyay USA waa George Washington.","options":["Run","Been"],"correct":"Run"},
  {"question":"Facebook waxaa la aasaasay 2004.","options":["Run","Been"],"correct":"Run"},
  {"question":"iPhone-ka ugu horreeyay waxaa la soo saaray 2007.","options":["Run","Been"],"correct":"Run"},
  {"question":"Python waxaa sameeyay Guido van Rossum.","options":["Run","Been"],"correct":"Run"},
  {"question":"Linux waxaa sameeyay Linus Torvalds.","options":["Run","Been"],"correct":"Run"},
  {"question":"RAM waxay u dhigan tahay Random Access Memory.","options":["Run","Been"],"correct":"Run"},
  {"question":"HTML waxay u dhigan tahay HyperText Markup Language.","options":["Run","Been"],"correct":"Run"},
  {"question":"URL waxay u dhigan tahay Uniform Resource Locator.","options":["Run","Been"],"correct":"Run"},
  {"question":"USB waxay u dhigan tahay Universal Serial Bus.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Pakistan waa Islamabad.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Japan waa Tokyo.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda South Korea waa Seoul.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Indonesia waa Jakarta.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Nigeria waa Abuja.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Morocco waa Rabat.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Algeria waa Algiers.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Libya waa Tripoli.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Sweden waa Stockholm.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Norway waa Oslo.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Poland waa Warsaw.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Ukraine waa Kyiv.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Iran waa Tehran.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada juz'yada Qur'aanka waa 30.","options":["Run","Been"],"correct":"Run"},
  {"question":"Nabi Ibraahim (AS) wuxuu dhisay Kacbada.","options":["Run","Been"],"correct":"Run"},
  {"question":"Suuradda 36 ee Qur'aanka waa Yaasiin.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada Nebiyada Ulul-Cazm waa 5.","options":["Run","Been"],"correct":"Run"},
  {"question":"Luuqadda Soomaaliga si rasmi ah loo qoray 1972.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda gobolka Bay waa Baidoa.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda gobolka Mudug waa Gaalkacyo.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda gobolka Bari waa Boosaaso.","options":["Run","Been"],"correct":"Run"},
  {"question":"Webiga ugu dhaadheer adduunka waa Niil.","options":["Run","Been"],"correct":"Run"},
  {"question":"Buurta ugu sarreysa adduunka waa Everest.","options":["Run","Been"],"correct":"Run"},
  {"question":"Nooca dhiigga ugu guud adduunka waa O+.","options":["Run","Been"],"correct":"Run"},
  {"question":"Heerkulka jirka bini'aadamka caadiga waa 37°C.","options":["Run","Been"],"correct":"Run"},
  {"question":"Dhibcaha biyuhu karkaraan waa 100°C.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada lafahaa jirka bini'aadamka waa 206.","options":["Run","Been"],"correct":"Run"},
  {"question":"17 × 17 = 289.","options":["Run","Been"],"correct":"Run"},
  {"question":"15% of 200 = 30.","options":["Run","Been"],"correct":"Run"},
  {"question":"√49 = 7.","options":["Run","Been"],"correct":"Run"},
  {"question":"0.5 × 0.5 = 0.25.","options":["Run","Been"],"correct":"Run"},
  {"question":"Suez Canal waxaa la furay 1869.","options":["Run","Been"],"correct":"Run"},
  {"question":"Nelson Mandela madaxweyne noqday 1994.","options":["Run","Been"],"correct":"Run"},
  {"question":"Google waxaa la aasaasay 1998.","options":["Run","Been"],"correct":"Run"},
  {"question":"OS-ka Apple iPhoneyaasha waa iOS.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda gobolka Jubbada Sare waa Bu'aale.","options":["Run","Been"],"correct":"Run"},
  {"question":"World Cup 2022 ku guulaystay kooxda Argentina.","options":["Run","Been"],"correct":"Run"},
  {"question":"Brazil wuxuu FIFA World Cup 5 jeer ku guulaystay.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada ciyaaryahanada volleyball koox waa 6.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada innings baseball waa 9.","options":["Run","Been"],"correct":"Run"},
  {"question":"Olympics-ka 4 sannadba mar ayuu dhacaa.","options":["Run","Been"],"correct":"Run"},
  {"question":"Plural of 'tooth' waa 'teeth'.","options":["Run","Been"],"correct":"Run"},
  {"question":"Plural of 'foot' waa 'feet'.","options":["Run","Been"],"correct":"Run"},
  {"question":"Past tense of 'fly' waa 'flew'.","options":["Run","Been"],"correct":"Run"},
  {"question":"Past tense of 'run' waa 'ran'.","options":["Run","Been"],"correct":"Run"},
  {"question":"Past tense of 'swim' waa 'swam'.","options":["Run","Been"],"correct":"Run"},
  {"question":"Past tense of 'write' waa 'wrote'.","options":["Run","Been"],"correct":"Run"},
  {"question":"Plural of 'man' waa 'men'.","options":["Run","Been"],"correct":"Run"},
  {"question":"7 × 8 = 56.","options":["Run","Been"],"correct":"Run"},
  {"question":"8 × 9 = 72.","options":["Run","Been"],"correct":"Run"},
  {"question":"3 × 3 = 9.","options":["Run","Been"],"correct":"Run"},
  {"question":"4 × 4 = 16.","options":["Run","Been"],"correct":"Run"},
  {"question":"11 × 11 = 121.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Sacuudiga waa Riyadh.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Imaaraatka waa Abu Dhabi.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Qadar waa Doha.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Kenya waa Nairobi.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Itoobiya waa Addis Ababa.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Ruushka waa Moscow.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Kanada waa Ottawa.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Faransiiska waa Paris.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Jarmalka waa Berlin.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Ingiriiska waa London.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Hindiya waa New Delhi.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Shiinaha waa Beijing.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Masar waa Cairo.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Turkiga waa Ankara.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Jabuuti waa Djibouti.","options":["Run","Been"],"correct":"Run"},
  {"question":"Nabi Muxamed (CSW) wuxuu ku dhashay Makka.","options":["Run","Been"],"correct":"Run"},
  {"question":"Badda ugu weyn adduunka waa Baasifig.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada xagasha saddex-xagalka waa 180°.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada xagasha afar-xagalka waa 360°.","options":["Run","Been"],"correct":"Run"},
  {"question":"Cunto cagaaran waxay samaysan tahay klorofiil.","options":["Run","Been"],"correct":"Run"},
  {"question":"Xubinta jirka nuujinta oksijiinta waa Sambabbada.","options":["Run","Been"],"correct":"Run"},
  {"question":"Dheriska iftiinka saniyaddii waa 300,000 km/s.","options":["Run","Been"],"correct":"Run"},
  {"question":"Xayawaanka ugu weyn adduunka waa Blue Whale.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Woqooyi Galbeed waa Hargeysa.","options":["Run","Been"],"correct":"Run"},
  {"question":"Maalin Xorriyadda Waqooyi Soomaaliya waa 26 Juun.","options":["Run","Been"],"correct":"Run"},
  {"question":"Xubinta jirka nuujinta dhiigga waa Wadnaha.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada garaaca wadnaha daqiiqadda caadiga waa 60-100.","options":["Run","Been"],"correct":"Run"},
  {"question":"CPU waxaa loola jeedaa Central Processing Unit.","options":["Run","Been"],"correct":"Run"},
  {"question":"Madaxweynihii ugu horreeyay Soomaaliya waa Aadan Cadde.","options":["Run","Been"],"correct":"Run"},
  {"question":"Maalin Xorriyadda Koonfurta Soomaaliya waa 1 Luulyo.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda gobolka Hiiraan waa Beledweyne.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda gobolka Sanaag waa Ceerigaavo.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada gobollada Soomaaliya waa 18.","options":["Run","Been"],"correct":"Run"},
  {"question":"Webiga ugu dhaadheer Soomaaliya waa Juba.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada sanadaha qarni waa 100.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada bilaha sanadka waa 12.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada saacadaha maalinta waa 24.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada maalinta toddobaadka waa 7.","options":["Run","Been"],"correct":"Run"},
  {"question":"12² = 144.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada caleemaha bandhiga waa 118.","options":["Run","Been"],"correct":"Run"},
  {"question":"Dalka ugu weyn adduunka waa Ruushka.","options":["Run","Been"],"correct":"Run"},
  {"question":"Dalkii ugu horreeyay ee gaadhay dayaxa waa Ameerika.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada Suurtada Qur'aanka waa 114.","options":["Run","Been"],"correct":"Run"},
  {"question":"Halqabihii Islaamkii ugu horreeyay waa Abuu Bakr.","options":["Run","Been"],"correct":"Run"},
  {"question":"Sannadkii Hijriga bilaabatay waa 622 M.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada halqabihii Raashidiin waa 4.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada fariidhyada Islaamka waa 5.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda gobolka Gedo waa Garbahaareey.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Puntland waa Garoowe.","options":["Run","Been"],"correct":"Run"},
  {"question":"Carboonka (Carbon) lambarka atoomiga waa 6.","options":["Run","Been"],"correct":"Run"},
  {"question":"Hantida ugu qaali badan adduunka waa Damaantiirka.","options":["Run","Been"],"correct":"Run"},
  {"question":"π ilaa labo meelood waa 3.14.","options":["Run","Been"],"correct":"Run"},
  {"question":"Xiddigta ugu dhowaanta qorraxda waa Proxima Centauri.","options":["Run","Been"],"correct":"Run"},
  {"question":"OS-ka Android waxaa sameeyay Google.","options":["Run","Been"],"correct":"Run"}
];

// Remove duplicates by question text
const existingTexts = new Set(existing.map(q => q.question));
const unique = newQ.filter(q => !existingTexts.has(q.question));
console.log('New unique questions:', unique.length);

const combined = [...existing, ...unique];
console.log('Total after merge:', combined.length);

fs.writeFileSync(FILE, JSON.stringify(combined, null, 2), 'utf8');
console.log('Done! Saved to', FILE);
