const fs = require('fs');
const path = require('path');
const FILE = path.join(__dirname, '..', 'data', 'questions', 'team.json');
const existing = JSON.parse(fs.readFileSync(FILE, 'utf8'));
const existingTexts = new Set(existing.map(q => q.question));
console.log('Current:', existing.length);

const newQ = [
  // ── MC: Caalamka ──
  {"question":"Caasimadda Spain waa?","options":["Barcelona","Seville","Valencia","Madrid"],"correct":"Madrid"},
  {"question":"Caasimadda Italy waa?","options":["Milan","Naples","Florence","Rome"],"correct":"Rome"},
  {"question":"Caasimadda Portugal waa?","options":["Porto","Faro","Braga","Lisbon"],"correct":"Lisbon"},
  {"question":"Caasimadda Netherlands waa?","options":["Rotterdam","The Hague","Utrecht","Amsterdam"],"correct":"Amsterdam"},
  {"question":"Caasimadda Belgium waa?","options":["Antwerp","Ghent","Liège","Brussels"],"correct":"Brussels"},
  {"question":"Caasimadda Switzerland waa?","options":["Zurich","Geneva","Basel","Bern"],"correct":"Bern"},
  {"question":"Caasimadda Austria waa?","options":["Graz","Salzburg","Linz","Vienna"],"correct":"Vienna"},
  {"question":"Caasimadda Greece waa?","options":["Thessaloniki","Patras","Heraklion","Athens"],"correct":"Athens"},
  {"question":"Caasimadda Hungary waa?","options":["Debrecen","Miskolc","Pécs","Budapest"],"correct":"Budapest"},
  {"question":"Caasimadda Romania waa?","options":["Cluj-Napoca","Timișoara","Iași","Bucharest"],"correct":"Bucharest"},
  {"question":"Caasimadda Serbia waa?","options":["Novi Sad","Niš","Kragujevac","Belgrade"],"correct":"Belgrade"},
  {"question":"Caasimadda Croatia waa?","options":["Split","Rijeka","Osijek","Zagreb"],"correct":"Zagreb"},
  {"question":"Caasimadda Czech Republic waa?","options":["Brno","Ostrava","Plzeň","Prague"],"correct":"Prague"},
  {"question":"Caasimadda Denmark waa?","options":["Aarhus","Odense","Aalborg","Copenhagen"],"correct":"Copenhagen"},
  {"question":"Caasimadda Finland waa?","options":["Tampere","Turku","Oulu","Helsinki"],"correct":"Helsinki"},
  // ── MC: Saynis cusub ──
  {"question":"Tirada caloosha bini'aadamka ee weyn waa?","options":["1","2","3","4"],"correct":"1"},
  {"question":"Xubinta jirka ee samaysa hormoonada waa?","options":["Sambabbada","Beerka","Kelyaha","Glandka"],"correct":"Glandka"},
  {"question":"Tirada ilkaha weynta bini'aadamka waa?","options":["28","30","32","34"],"correct":"32"},
  {"question":"Nooca xayndaabka (virus) ugu habboon waa?","options":["Antibiotics","Vaccine","Surgery","Herbs"],"correct":"Vaccine"},
  {"question":"Meeraha ugu kulul adduunka waa?","options":["Earth","Venus","Mars","Mercury"],"correct":"Venus"},
  {"question":"Tirada caleemaha dayaxa (moons) Jupiter leeyahay ee ugu weyn waa?","options":["2","4","8","16"],"correct":"4"},
  {"question":"Xayawaanka keliya ee diirada isa-leh ayaa jira — noocyaada gaaridda (fastest land animal)?","options":["Lion","Horse","Cheetah","Ostrich"],"correct":"Cheetah"},
  {"question":"Tirada caloosha lo'da waa?","options":["2","3","4","5"],"correct":"4"},
  {"question":"Dareenka ugu dhow elektrisite-ka (element) waa?","options":["Iron","Copper","Gold","Silver"],"correct":"Silver"},
  {"question":"Meeraha ugu qabow nidaamka qorraxeed waa?","options":["Uranus","Saturn","Mars","Neptune"],"correct":"Neptune"},
  // ── MC: Ciyaaraha ──
  {"question":"Tirada ciyaaryahanada basketball koox waa?","options":["4","5","6","7"],"correct":"5"},
  {"question":"Tirada ciyaaryahanada rugby union koox waa?","options":["11","13","15","17"],"correct":"15"},
  {"question":"Tirada ciyaaryahanada hockey (field) koox waa?","options":["9","10","11","12"],"correct":"11"},
  {"question":"Tirada ciyaaryahanada American football koox waa?","options":["9","11","13","15"],"correct":"11"},
  {"question":"World Cup 2026 waxay dhici doontaa?","options":["Yurub","Aasiya","Koonfur Ameerika","USA/Canada/Mexico"],"correct":"USA/Canada/Mexico"},
  {"question":"Tennis-ka Grand Slam-ka kowaad ee sanadka waa?","options":["Wimbledon","US Open","French Open","Australian Open"],"correct":"Australian Open"},
  {"question":"Usain Bolt wuxuu ku caan baxay ciyaaraha?","options":["Boxing","Swimming","Athletics (sprint)","Cycling"],"correct":"Athletics (sprint)"},
  {"question":"Dalka kubadda cagta FIFA ranking-ka koowaad (2022) ku jiray waa?","options":["Brazil","Argentina","France","Spain"],"correct":"Brazil"},
  {"question":"FIFA World Cup 2018 waxay dhacday?","options":["Brazil","Qatar","Germany","Russia"],"correct":"Russia"},
  {"question":"FIFA World Cup 2014 waxay dhacday?","options":["Russia","Germany","Brazil","Argentina"],"correct":"Brazil"},
  // ── MC: Teknoolajiyada cusub ──
  {"question":"AI waxay u dhigan tahay?","options":["Automated Input","Artificial Intelligence","Advanced Internet","Automated Integration"],"correct":"Artificial Intelligence"},
  {"question":"Wi-Fi waxay u dhigan tahay?","options":["Wireless Fidelity","Wireless Frequency","Wide Fidelity","World Internet"],"correct":"Wireless Fidelity"},
  {"question":"GPS waxay u dhigan tahay?","options":["General Positioning System","Global Placement System","Global Positioning System","Guided Positioning System"],"correct":"Global Positioning System"},
  {"question":"PDF waxay u dhigan tahay?","options":["Portable Document Format","Printed Document File","Personal Data Format","Portable Data File"],"correct":"Portable Document Format"},
  {"question":"GB waxay u dhigan tahay (xogta)?","options":["General Bytes","Gigabytes","Global Bits","Gated Bytes"],"correct":"Gigabytes"},
  {"question":"MB waxay u dhigan tahay (xogta)?","options":["Megabytes","Multibit","Managed Bytes","Mapped Bytes"],"correct":"Megabytes"},
  {"question":"Luuqadda barnaamijka ee websites-ka front-end ugu badan isticmaala waa?","options":["Python","Java","C++","JavaScript"],"correct":"JavaScript"},
  {"question":"IP waxay u dhigan tahay (networking)?","options":["Internet Processor","Internal Protocol","Internet Protocol","Integrated Process"],"correct":"Internet Protocol"},
  {"question":"SSD waxay u dhigan tahay?","options":["Super Speed Drive","Solid State Drive","Single Storage Device","System Storage Disk"],"correct":"Solid State Drive"},
  {"question":"API waxay u dhigan tahay?","options":["Application Processing Interface","Automated Program Integration","Application Programming Interface","Advanced Protocol Interface"],"correct":"Application Programming Interface"},
  // ── MC: Soomaaliya dheeraad ──
  {"question":"Caasimadda maamul-goboleedka Hirshabeelle waa?","options":["Beledweyne","Jawhar","Balcad","Jowhar"],"correct":"Jowhar"},
  {"question":"Caasimadda maamul-goboleedka Jubbaland waa?","options":["Baraawe","Bu'aale","Baardheere","Kismaayo"],"correct":"Kismaayo"},
  {"question":"Caasimadda maamul-goboleedka Koonfur Galbeed waa?","options":["Baardheere","Luuq","Wajid","Baidoa"],"correct":"Baidoa"},
  {"question":"Caasimadda maamul-goboleedka SSC-Khaatumo waa?","options":["Ceerigaavo","Laascaanood","Qardho","Taleex"],"correct":"Laascaanood"},
  {"question":"Magaalada ugu weyn Somaliland waa?","options":["Burco","Berbera","Ceerigaavo","Hargeysa"],"correct":"Hargeysa"},
  {"question":"Ciida gaadhitaanka Koonfurta Soomaaliya sanadkiisa waa?","options":["1959","1960","1961","1962"],"correct":"1960"},
  {"question":"Koonfurta iyo Waqooyi Soomaaliya waxay midoobeen?","options":["26 Juun 1960","1 Luulyo 1960","21 Oktoobar 1969","26 Juun 1961"],"correct":"1 Luulyo 1960"},
  {"question":"Doorashadii Soomaaliya ee 2021-2022 madaxweynaha lagu doortay waa?","options":["Farmaajo","Xasan Sheekh","Xassan Cali","Cabdiweli"],"correct":"Xasan Sheekh"},
  {"question":"Gobolka ay ku taallo magaalada Baardheere waa?","options":["Bay","Gedo","Bakool","Jubbada Dhexe"],"correct":"Gedo"},
  {"question":"Webiga Juba wuxuu galaa badda?","options":["Badda Cas","Badda Hindiya","Gacanka Cadmeed","Badda Mediterranean"],"correct":"Badda Hindiya"},

  // ── BEEN: Caasimaddo cusub ──
  {"question":"Caasimadda Spain waa Barcelona.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Italy waa Milan.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Portugal waa Porto.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Netherlands waa Rotterdam.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Belgium waa Antwerp.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Switzerland waa Zurich.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Austria waa Salzburg.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Greece waa Thessaloniki.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Hungary waa Debrecen.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Romania waa Cluj-Napoca.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Czech Republic waa Brno.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Denmark waa Aarhus.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Finland waa Tampere.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Serbia waa Novi Sad.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Croatia waa Split.","options":["Run","Been"],"correct":"Been"},
  // ── BEEN: Saynis ──
  {"question":"Meeraha ugu kulul adduunka waa Mercury.","options":["Run","Been"],"correct":"Been"},
  {"question":"Xayawaanka ugu dhaqso badan dhulka waa Lion.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada ciyaaryahanada basketball koox waa 6.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada ciyaaryahanada rugby union koox waa 13.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada ilkaha weynta bini'aadamka waa 28.","options":["Run","Been"],"correct":"Been"},
  {"question":"Meeraha ugu qabow nidaamka qorraxeed waa Uranus.","options":["Run","Been"],"correct":"Been"},
  {"question":"AI waxay u dhigan tahay Automated Input.","options":["Run","Been"],"correct":"Been"},
  {"question":"Wi-Fi waxay u dhigan tahay Wide Fidelity.","options":["Run","Been"],"correct":"Been"},
  {"question":"GPS waxay u dhigan tahay General Positioning System.","options":["Run","Been"],"correct":"Been"},
  {"question":"PDF waxay u dhigan tahay Printed Document File.","options":["Run","Been"],"correct":"Been"},
  {"question":"SSD waxay u dhigan tahay Super Speed Drive.","options":["Run","Been"],"correct":"Been"},
  {"question":"API waxay u dhigan tahay Application Processing Interface.","options":["Run","Been"],"correct":"Been"},
  {"question":"IP waxay u dhigan tahay Internet Processor.","options":["Run","Been"],"correct":"Been"},
  {"question":"JavaScript waa luuqadda Python-ka.","options":["Run","Been"],"correct":"Been"},
  {"question":"World Cup 2026 waxay dhici doontaa Yurub.","options":["Run","Been"],"correct":"Been"},
  {"question":"World Cup 2018 waxay dhacday Brazil.","options":["Run","Been"],"correct":"Been"},
  {"question":"World Cup 2014 waxay dhacday Russia.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tennis Australian Open waa Grand Slam-ka ugu dambeeyay sanadka.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada ciyaaryahanada American football koox waa 9.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Jubbaland waa Baraawe.","options":["Run","Been"],"correct":"Been"},
  {"question":"Caasimadda Koonfur Galbeed waa Baardheere.","options":["Run","Been"],"correct":"Been"},
  {"question":"Koonfurta iyo Waqooyi Soomaaliya waxay midoobeen 26 Juun 1960.","options":["Run","Been"],"correct":"Been"},
  {"question":"Webiga Juba wuxuu galaa Badda Cas.","options":["Run","Been"],"correct":"Been"},
  {"question":"Gobolka Baardheere ku taallo waa Bay.","options":["Run","Been"],"correct":"Been"},
  // ── BEEN: Xisaab cusub ──
  {"question":"5 × 5 = 30.","options":["Run","Been"],"correct":"Been"},
  {"question":"6 × 6 = 30.","options":["Run","Been"],"correct":"Been"},
  {"question":"7 × 7 = 42.","options":["Run","Been"],"correct":"Been"},
  {"question":"10 × 10 = 90.","options":["Run","Been"],"correct":"Been"},
  {"question":"4 × 6 = 20.","options":["Run","Been"],"correct":"Been"},
  {"question":"3 × 8 = 21.","options":["Run","Been"],"correct":"Been"},
  {"question":"9 × 4 = 32.","options":["Run","Been"],"correct":"Been"},
  {"question":"12 × 8 = 88.","options":["Run","Been"],"correct":"Been"},
  {"question":"11 × 9 = 90.","options":["Run","Been"],"correct":"Been"},
  {"question":"6 × 9 = 52.","options":["Run","Been"],"correct":"Been"},
  {"question":"√81 = 7.","options":["Run","Been"],"correct":"Been"},
  {"question":"√100 = 11.","options":["Run","Been"],"correct":"Been"},
  {"question":"√36 = 7.","options":["Run","Been"],"correct":"Been"},
  {"question":"√16 = 5.","options":["Run","Been"],"correct":"Been"},
  {"question":"2⁵ = 16.","options":["Run","Been"],"correct":"Been"},
  {"question":"2⁶ = 32.","options":["Run","Been"],"correct":"Been"},
  {"question":"3² = 6.","options":["Run","Been"],"correct":"Been"},
  {"question":"4² = 20.","options":["Run","Been"],"correct":"Been"},
  {"question":"5² = 20.","options":["Run","Been"],"correct":"Been"},
  {"question":"10² = 1000.","options":["Run","Been"],"correct":"Been"},
  {"question":"25% of 400 waa 75.","options":["Run","Been"],"correct":"Been"},
  {"question":"10% of 500 waa 60.","options":["Run","Been"],"correct":"Been"},
  {"question":"75% of 200 waa 100.","options":["Run","Been"],"correct":"Been"},
  {"question":"30% of 100 waa 25.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada xagasha pentagon waa 4.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada xagasha octagon waa 6.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada xagasha triangle waa 4.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada dhinacyada cube waa 4.","options":["Run","Been"],"correct":"Been"},
  {"question":"Tirada dhinacyada pyramid (4-sided base) waa 3.","options":["Run","Been"],"correct":"Been"},
  {"question":"1 kilometer waxay la mid tahay 10 mitir.","options":["Run","Been"],"correct":"Been"},
  // ── BEEN: Luuqad ──
  {"question":"Past tense of 'see' waa 'seed'.","options":["Run","Been"],"correct":"Been"},
  {"question":"Past tense of 'break' waa 'breaked'.","options":["Run","Been"],"correct":"Been"},
  {"question":"Past tense of 'bring' waa 'bringed'.","options":["Run","Been"],"correct":"Been"},
  {"question":"Past tense of 'buy' waa 'buyed'.","options":["Run","Been"],"correct":"Been"},
  {"question":"Past tense of 'drive' waa 'drived'.","options":["Run","Been"],"correct":"Been"},
  {"question":"Past tense of 'fall' waa 'falled'.","options":["Run","Been"],"correct":"Been"},
  {"question":"Past tense of 'fight' waa 'fighted'.","options":["Run","Been"],"correct":"Been"},
  {"question":"Plural of 'ox' waa 'oxes'.","options":["Run","Been"],"correct":"Been"},
  {"question":"Plural of 'goose' waa 'gooses'.","options":["Run","Been"],"correct":"Been"},
  {"question":"Plural of 'leaf' waa 'leafs'.","options":["Run","Been"],"correct":"Been"},
  {"question":"'Enormous' waa opposite-ka 'large'.","options":["Run","Been"],"correct":"Been"},
  {"question":"'Ancient' means 'future'.","options":["Run","Been"],"correct":"Been"},
  {"question":"'Rapid' means 'heavy'.","options":["Run","Been"],"correct":"Been"},
  {"question":"'Depart' means 'arrive'.","options":["Run","Been"],"correct":"Been"},
  {"question":"'Full' is the opposite of 'open'.","options":["Run","Been"],"correct":"Been"},
  // ── RUN cusub ──
  {"question":"Caasimadda Spain waa Madrid.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Italy waa Rome.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Portugal waa Lisbon.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Netherlands waa Amsterdam.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Belgium waa Brussels.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Switzerland waa Bern.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Austria waa Vienna.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Greece waa Athens.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Czech Republic waa Prague.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Denmark waa Copenhagen.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Finland waa Helsinki.","options":["Run","Been"],"correct":"Run"},
  {"question":"Meeraha ugu kulul nidaamka qorraxeed waa Venus.","options":["Run","Been"],"correct":"Run"},
  {"question":"Xayawaanka ugu dhaqso badan dhulka waa Cheetah.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada ciyaaryahanada basketball koox waa 5.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada ciyaaryahanada rugby union koox waa 15.","options":["Run","Been"],"correct":"Run"},
  {"question":"AI waxay u dhigan tahay Artificial Intelligence.","options":["Run","Been"],"correct":"Run"},
  {"question":"Wi-Fi waxay u dhigan tahay Wireless Fidelity.","options":["Run","Been"],"correct":"Run"},
  {"question":"GPS waxay u dhigan tahay Global Positioning System.","options":["Run","Been"],"correct":"Run"},
  {"question":"PDF waxay u dhigan tahay Portable Document Format.","options":["Run","Been"],"correct":"Run"},
  {"question":"SSD waxay u dhigan tahay Solid State Drive.","options":["Run","Been"],"correct":"Run"},
  {"question":"API waxay u dhigan tahay Application Programming Interface.","options":["Run","Been"],"correct":"Run"},
  {"question":"World Cup 2026 waxay dhici doontaa USA/Canada/Mexico.","options":["Run","Been"],"correct":"Run"},
  {"question":"World Cup 2018 waxay dhacday Russia.","options":["Run","Been"],"correct":"Run"},
  {"question":"World Cup 2014 waxay dhacday Brazil.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Jubbaland waa Kismaayo.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Koonfur Galbeed waa Baidoa.","options":["Run","Been"],"correct":"Run"},
  {"question":"Koonfurta iyo Waqooyi Soomaaliya waxay midoobeen 1 Luulyo 1960.","options":["Run","Been"],"correct":"Run"},
  {"question":"Webiga Juba wuxuu galaa Badda Hindiya.","options":["Run","Been"],"correct":"Run"},
  {"question":"5 × 5 = 25.","options":["Run","Been"],"correct":"Run"},
  {"question":"6 × 6 = 36.","options":["Run","Been"],"correct":"Run"},
  {"question":"7 × 7 = 49.","options":["Run","Been"],"correct":"Run"},
  {"question":"10 × 10 = 100.","options":["Run","Been"],"correct":"Run"},
  {"question":"√81 = 9.","options":["Run","Been"],"correct":"Run"},
  {"question":"√100 = 10.","options":["Run","Been"],"correct":"Run"},
  {"question":"√36 = 6.","options":["Run","Been"],"correct":"Run"},
  {"question":"2⁵ = 32.","options":["Run","Been"],"correct":"Run"},
  {"question":"2⁶ = 64.","options":["Run","Been"],"correct":"Run"},
  {"question":"10² = 100.","options":["Run","Been"],"correct":"Run"},
  {"question":"25% of 400 waa 100.","options":["Run","Been"],"correct":"Run"},
  {"question":"10% of 500 waa 50.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada xagasha pentagon waa 5.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada xagasha octagon waa 8.","options":["Run","Been"],"correct":"Run"},
  {"question":"1 kilometer waxay la mid tahay 1000 mitir.","options":["Run","Been"],"correct":"Run"},
  {"question":"Past tense of 'see' waa 'saw'.","options":["Run","Been"],"correct":"Run"},
  {"question":"Past tense of 'break' waa 'broke'.","options":["Run","Been"],"correct":"Run"},
  {"question":"Past tense of 'buy' waa 'bought'.","options":["Run","Been"],"correct":"Run"},
  {"question":"Past tense of 'fall' waa 'fell'.","options":["Run","Been"],"correct":"Run"},
  {"question":"Plural of 'ox' waa 'oxen'.","options":["Run","Been"],"correct":"Run"},
  {"question":"Plural of 'goose' waa 'geese'.","options":["Run","Been"],"correct":"Run"},
  {"question":"Plural of 'leaf' waa 'leaves'.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada maalinta Febraayo ee sanadka caadiga ah waa 28.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada daqiiqadaha saacadda waa 60.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada ilkaha weynta bini'aadamka waa 32.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda Hirshabeelle waa Jowhar.","options":["Run","Been"],"correct":"Run"},
  {"question":"Caasimadda SSC-Khaatumo waa Laascaanood.","options":["Run","Been"],"correct":"Run"},
  {"question":"Magaalada ugu weyn Somaliland waa Hargeysa.","options":["Run","Been"],"correct":"Run"},
  {"question":"Tirada gobollada Soomaaliya waa 18.","options":["Run","Been"],"correct":"Run"}
];

const unique = newQ.filter(q => !existingTexts.has(q.question));
console.log('New unique:', unique.length);
const combined = [...existing, ...unique];
console.log('Total:', combined.length);
fs.writeFileSync(FILE, JSON.stringify(combined, null, 2), 'utf8');
console.log('Done!');
